"""Contrato versionado: draft con evidencia y contrato validado."""

from kliptych.contract.draft import (
    AssetDraft,
    AssetsDraft,
    AttributionDraft,
    CaptionRulesDraft,
    ContractDraft,
    DurationDraft,
    GeoTargetDraft,
    LanguagesDraft,
    LinkRulesDraft,
    OfficialAudioDraft,
    PlatformDraft,
    RuleSetDraft,
    WatermarkDraft,
)
from kliptych.contract.enums import AttributionType, AudioRule, Format, Mode, Platform
from kliptych.contract.evidence import Confidence, FieldCandidate, SourceEvidence
from kliptych.contract.schema import (
    AnalyticsProofRequired,
    AssetBundle,
    AssetRef,
    Attribution,
    CaptionRules,
    Contract,
    DurationRange,
    GeoTarget,
    Languages,
    LinkRules,
    MinViewsForPayout,
    OfficialAudio,
    PlatformRules,
    RuleSet,
    Watermark,
)

__all__ = [
    "AnalyticsProofRequired",
    "AssetBundle",
    "AssetDraft",
    "AssetRef",
    "AssetsDraft",
    "Attribution",
    "AttributionDraft",
    "AttributionType",
    "AudioRule",
    "CaptionRules",
    "CaptionRulesDraft",
    "Confidence",
    "Contract",
    "ContractDraft",
    "DurationDraft",
    "DurationRange",
    "FieldCandidate",
    "Format",
    "GeoTarget",
    "GeoTargetDraft",
    "Languages",
    "LanguagesDraft",
    "LinkRules",
    "LinkRulesDraft",
    "MinViewsForPayout",
    "Mode",
    "OfficialAudio",
    "OfficialAudioDraft",
    "Platform",
    "PlatformDraft",
    "PlatformRules",
    "RuleSet",
    "RuleSetDraft",
    "SourceEvidence",
    "Watermark",
    "WatermarkDraft",
]
